### ISSUE TITLE
SRS V1 - Create System Requirements Specification

### ISSUE THREAD

**Issue by samanthacombs** [AVanDeBrook/c-dependency-graph#21]
### Story
As a stakeholder, I want a System Requirements Specification document, so that I can read the outline the product overview, specific requirements, and any supporting material.

### Demo Criteria
* A complete SRS document created from the template/examples provided on Canvas.

**Comment by corrinacoffee** [comment]
Closing issue because V1 was submitted and V2 has a story card written for it.
