### ISSUE TITLE
SDD V1 - Create System Design Document

### ISSUE THREAD

**Issue by samanthacombs** [AVanDeBrook/c-dependency-graph#29]
### Story
As a stakeholder, I want there to be a System Design Document, so that I can understand the project's system architecture, human-machine and external interfaces, detailed design, and system integrity controls.

### Demo Criteria
* A complete SDD document from the template/examples provided on Canvas.

**Comment by corrinacoffee** [comment]
Closing issue because V1 was submitted and V2 has a story card written for it.
