### ISSUE TITLE
Infrastructure Story 2 - Chapter 2 - Learn DOT

### ISSUE THREAD

**Issue by samanthacombs** [AVanDeBrook/c-dependency-graph#7]
DOT language 
- [x] Each member must have a basic understanding of DOT language
   - [x] Know how node and edge attributes are defined
   - [x] Know how to differentiate between graph types
   - [x] Know how to use sub-graphs
   - [x] Know how nodes and edges are defined
   - [x] Know how to reference graph and node IDs
- [x] Each member must be able to explain the means of nodes and edges that are generated DOT files by Doxygen

**Comment by AVanDeBrook** [comment]
Expanding "Each member must have a basic understanding of dot language":
- [ ] Know how node and edge attributes are defined
- [ ] Know how to differentiate between graph types
- [ ] Know how to use sub-graphs
- [ ] Know how nodes and edges are defined
- [ ] Know how to reference graph and node IDs
